window.extraQuestions = [
  [7,"Projektplanering, roller och samarbete","Vad kännetecknar ett projekt?","Det har ett tydligt mål, begränsad tid och resurser samt planerade arbetsuppgifter."],
  [7,"Projektplanering, roller och samarbete","Vilka vanliga faser har ett IT-projekt?","Planering, design, utveckling, testning och lansering."],
  [7,"Projektplanering, roller och samarbete","Vad ska en tydlig projektplan beskriva?","Mål, arbetsuppgifter, tidsplan, resurser, ansvar och hur arbetet ska följas upp."],
  [7,"Projektplanering, roller och samarbete","Varför behövs tydliga roller i ett projekt?","Så att ansvar fördelas, viktiga uppgifter inte missas och samarbetet blir effektivare."],
  [7,"Projektplanering, roller och samarbete","Vad kännetecknar ett bra projektsamarbete?","Tydlig kommunikation, gemensamma mål, ansvarstagande och regelbunden uppföljning."],
  [8,"Arbetsmetoder och agila projekt","Vad skiljer traditionell projektplanering från agilt arbete?","Traditionell planering följer en mer fast plan, medan agilt arbete omprövar lösningen i korta iterationer."],
  [8,"Arbetsmetoder och agila projekt","Vad betyder iterativ utveckling?","Att bygga, testa, utvärdera och förbättra lösningen i återkommande omgångar."],
  [8,"Arbetsmetoder och agila projekt","Vad är en sprint?","En kort, avgränsad arbetsperiod där teamet genomför utvalda uppgifter och levererar ett resultat."],
  [8,"Arbetsmetoder och agila projekt","Varför är dokumentation viktig i projekt?","Den bevarar beslut, krav, tester och förändringar så att arbetet kan förstås och följas upp."],
  [8,"Arbetsmetoder och agila projekt","När passar ett agilt arbetssätt särskilt bra?","När krav kan förändras och lösningen behöver utvecklas genom tät återkoppling och testning."],
  [9,"Programmeringsprocessen från problem till test","Vilka huvudsteg ingår i programmeringsprocessen?","Förstå problemet, planera lösningen, skriva kod och testa resultatet."],
  [9,"Programmeringsprocessen från problem till test","Varför ska problemet förstås innan kod skrivs?","För att tydliggöra indata, önskat resultat, krav och avgränsningar så att rätt problem löses."],
  [9,"Programmeringsprocessen från problem till test","Hur kan en lösning planeras före kodning?","Med exempelvis pseudokod, flödesschema och uppdelning i mindre delproblem."],
  [9,"Programmeringsprocessen från problem till test","Vilken uppgift har villkor och loopar?","Villkor låter programmet fatta beslut och loopar upprepar kod på ett kontrollerat sätt."],
  [9,"Programmeringsprocessen från problem till test","Varför ska ett program testas med flera slags indata?","För att kontrollera både normala fall, gränsfall och felaktiga värden."],
  [10,"Programförbättring, automatisering och kvalitet","Vad innebär det att förbättra ett program?","Att göra det exempelvis tydligare, snabbare, stabilare, säkrare eller lättare att använda."],
  [10,"Programförbättring, automatisering och kvalitet","Vad betyder automatisering?","Att låta ett program utföra återkommande uppgifter med liten eller ingen manuell hantering."],
  [10,"Programförbättring, automatisering och kvalitet","Vad är en bugg?","Ett fel i programmet som gör att det kraschar eller beter sig annorlunda än avsett."],
  [10,"Programförbättring, automatisering och kvalitet","Hur bidrar funktioner till programkvalitet?","De delar upp koden i namngivna, återanvändbara delar som blir lättare att läsa och testa."],
  [10,"Programförbättring, automatisering och kvalitet","Vad kännetecknar programkod med god kvalitet?","Den är korrekt, läsbar, testad, strukturerad, robust och möjlig att underhålla."]
];
